# Generated by Django 5.1 on 2024-08-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
